### ISSUE TITLE
Reintroduce Mac OSX Builds

### ISSUE THREAD

**Issue by carusology** [invio/Invio.Extensions.Reflection#18]
Got some odd messaging around cryptography packages not working in Travis CI. That needs to be addressed so Mac OSX builds can be reintroduced.

**Comment by carusology** [comment]
Here's [the message from Travis CI](https://travis-ci.org/invio/Invio.Extensions.Reflection/jobs/177853949):

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte* buf, Int32 num)
   at System.IO.Path.GetCryptoRandomBytes(Byte* bytes, Int32 byteCount)
   at System.IO.Path.GetRandomFileName()
   at Microsoft.DotNet.InternalAbstractions.TemporaryDirectory..ctor()
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateTemporaryDirectory()
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver..ctor()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
./build.sh: line 12:  2501 Abort trap: 6           dotnet restore
```

This shows that the `dotnet restore` command is failing. Early googling suggests this is a problem with the dotnet docker container not installing openssl properly.

**Comment by carusology** [comment]
Link to how Travis CI team tested their builds...

https://github.com/akoeplinger/travis-mono-test/blob/master/.travis.yml
